[server]
headless = true
runOnSave = true
enableXsrfProtection = true


[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif" 


[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true
